### ISSUE TITLE
Suggestion: Toggleable tooltips

### ISSUE THREAD

**Issue by DT-is-not-available** [b0iizz/minecraft-advancednbttooltip#14]
I am doing a lot with custom item names and lore, however it seems that all tooltip data such as the custom model data tooltip appears between the item name and the item lore. Could you make an option to disable extra tooltips or move extra information to the end of the entire tooltip? for example item name, lore, then what attributes are hidden/custom model data/ stuff like that.

**Comment by DT-is-not-available** [comment]
Could also be resolved by just making extra tooltips show when F3+H is enabled (advanced tooltips).

**Comment by b0iizz** [comment]
There are actually options for both of that! When you are using ModMenu there is a config for my mod. In this config you can toggle each Tooltip individually and move their position. It is however my fault for not talking about this at all anywhere.

**Comment by b0iizz** [comment]
I have now restructured the config to make it more accessible as well as added a Keybind to open that config. I hope this helps :)
