### ISSUE TITLE
[feature request] custom translation in .minecraft/config

### ISSUE THREAD

**Issue by Guanran928** [b0iizz/minecraft-advancednbttooltip#17]
custom translation in .minecraft/config so I can change repairCost to something like uwu cost or something

**Comment by b0iizz** [comment]
This should probably be possible with resource packs but don't quote me on that. I will look into it

**Comment by b0iizz** [comment]
So i looked into it for a bit and i have to say that it is probably not possible considering how localization is handled by minecraft itself. However: If you really want to rename Repair Cost to uwu cost I could add the lolcat (lol_us.json) language to the mods localization.
