### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Serega007RU** [b0iizz/minecraft-advancednbttooltip#20]
Crash with version 1.3.1 +
Crash occurs when you try to log in to a server or a single player
If I install version 1.3.0 then there is no such crash
[crash-2021-02-06_16.44.31-client.txt](https://github.com/b0iizz/minecraft-advancednbttooltip/files/5936893/crash-2021-02-06_16.44.31-client.txt)

**Comment by b0iizz** [comment]
Thank you for posting this! This has never happened to me during development so I didnt notice it.
This has something to do with the signs tooltip. To determine whether the tooltip will be applied, it checks if its a sign but for some reason that check is being called before it properly knows what a sign is...

**Comment by b0iizz** [comment]
Okay so I removed the function call that was responsible for the crash, it was not really necessary anyway (it was more like a redundancy thing). Please tell me if the crash still occurs when the next version is out.
