### ISSUE TITLE
The code for modified spawn eggs assumes that you're always and only changing what mob is produced.

### ISSUE THREAD

**Issue by edelsone** [b0iizz/minecraft-advancednbttooltip#23]
If a spawn egg has a custom EntityTag attribute that does not include an "id" subtag, the tooltip shows "`Entity: entity.`". Also, any other attributes being modified by EntityTag are not listed.

Here's an example of a modified creeper egg, for reference: `/give @p minecraft:creeper_spawn_egg{display:{Name:'{"text":"Speedy Creeper Spawn Egg"}'},EntityTag:{ExplosionRadius:5b,Fuse:1,Attributes:[{Name:generic.movementSpeed,Base:1.1}]}} 1`

**Comment by b0iizz** [comment]
Thanks for your feedback! I will wix this Entity: entity thing for sure but I am uncertain about displaying more information as I think it might get a bit crammed then. Might change my mind tho

**Comment by edelsone** [comment]
While it's clearly possible, I've never seen the EntityTag being used to completely change what mob a spawn egg produces. But I have seen instances of other details being modified, so I do hope that you choose to make all custom mob egg data available, even if you put it under a non-default option setting.

Thank you.

**Comment by b0iizz** [comment]
I changed it in the new version to show all NBT inside of "EntityTag"

**Comment by edelsone** [comment]
Yes, this is excellent. Thank you very much.
