### ISSUE TITLE
Add all the existing tooltips to `.minecraft/tooltips`

### ISSUE THREAD

**Issue by barraIhsan** [b0iizz/minecraft-advancednbttooltip#24]
So now, we can modify the existing tooltips?
It also works as a "tooltips example" if someone doesn't understand the tutorial from README. (I still didn't understand)

**Comment by b0iizz** [comment]
I'm actually working right now on doing that! It will be a while till its out though.

**Comment by b0iizz** [comment]
1.5.0 does what I envisioned for this feature so I'm closing this for now. I still want to improve the explanations of the format but I think its fine for now at least-
