### ISSUE TITLE
[Bug] update text is overwritten by Optifine version

### ISSUE THREAD

**Issue by barraIhsan** [b0iizz/minecraft-advancednbttooltip#25]
![image](https://user-images.githubusercontent.com/57800056/112829886-fa722200-90bb-11eb-8c97-64b862c88cfe.png)
I don't really good at English to explain it, but the text is just below the optifine version information, or maybe use the [ModUpdater](https://www.curseforge.com/minecraft/mc-mods/modupdater) Instead?

**Comment by b0iizz** [comment]
Thank you for showing this mod to me i will probably use something like this in the future! I was actually looking for a mod like this as the previous method is a bit crude as you can see!

**Comment by RooftopJoe** [comment]
People can use the Fabrilous Updater instead.
