### ISSUE TITLE
Help with custom tooltips

### ISSUE THREAD

**Issue by barraIhsan** [b0iizz/minecraft-advancednbttooltip#27]
this is the `explorer_map.json`
```json
{
	"text": {
		"id": "formatted",
		"color": "gray",
		"text": {
			"id": "mix",
			"texts": [
				"X : ",
				{
					"id": "nbt",
					"tag": "Decorations[].x"
				},
				" Z : ",
				{
					"id": "nbt",
					"tag": "Decorations[].z"
				}
			]
		}
	},
	"condition": {
		"id": "and",
		"conditions": [
			{
				"id": "is_item",
				"items": [
					"minecraft:filled_map"
				]
			},
			{
				"id": "tag_matches",
				"tag": "Decorations"
			}
		]
	}
}
```
But it didn't work and there is a bunch of error in log

(also very nice if you have discord server to ask something like this)

**Comment by b0iizz** [comment]
You have to specify an index at Decorations like Decorations[0].x or something like this. I plan to eventually change that so that it would then look at every element in the list but I need to rewrite some stuff to change that. Next update, I hope

**Comment by b0iizz** [comment]
the error is also from the tag_matches condition. "tag_matches" is for checking for a specific value the condition you were looking for is "has_tag"

**Comment by barraIhsan** [comment]
Wait, to reload custom tooltips, you just reload resourcepack (`F3 + T`) right?

**Comment by barraIhsan** [comment]
> the error is also from the tag_matches condition. "tag_matches" is for checking for a specific value the condition you were looking for is "has_tag"

oh ok

**Comment by barraIhsan** [comment]
[explorer_map.json](https://user-images.githubusercontent.com/57800056/113481265-b8355000-94c2-11eb-9494-10832924ed4c.png)
Its still not working, oh also I modified the compass and it also doesn't work
[compass.json](https://user-images.githubusercontent.com/57800056/113481281-d438f180-94c2-11eb-8f8a-e98d2feb9540.png)
(Doesnt put ! to make sure it doesn't fill out the entire issues chat)
Is it still in beta, so a lot of it doesn't work?

**Comment by b0iizz** [comment]
I have started coding the new version and this will work then (I tested it on a buried treasure map)
[code](https://user-images.githubusercontent.com/70597779/113482549-71822e80-949f-11eb-812f-d246d9375f94.JPG)

**Comment by barraIhsan** [comment]
It still doesnt work, also do you have a [discord](discord.com) acc to communicate better?

**Comment by b0iizz** [comment]
I do have a discord account but it didnt work because I didnt release the patch yet. I plan to release it today (I had kinda lost motivation the last few weeks)

**Comment by b0iizz** [comment]
There's also now a better way to do this now but I hope I can update the demonstration resource packs today
