### ISSUE TITLE
Bug: Update checker spams console with errors

### ISSUE THREAD

**Issue by Kylebartaous** [b0iizz/minecraft-advancednbttooltip#29]
Minecraft version:1.17.1
Fabric Loader version: 0.12.2
Fabric API version: 0.41.0
Adv nbt tool tips version: 1.6.0 build 4

Crash log: https://pastebin.com/GDPpGme7
 
An example of what i see then looking at the logs via gd launcher dev tools
![image](https://user-images.githubusercontent.com/11208209/137815346-3e30c7cc-215f-4a90-b51e-66a02794277a.png)

**Comment by Kylebartaous** [comment]
Changing my fabric loader version back from 0.12.2 to 0.11.7 and using the same fabric api version, adv nbt tool tips mod version, makes those errors not happen in the logs.

**Comment by b0iizz** [comment]
Yeah I think something has changed in the new loader. I was planning to remove the updatechecker anyways. I will use modupdater in future releases.

**Comment by b0iizz** [comment]
As this piece of code no longer exists in the new release it should be fixed now! Thank you for showing me this.
