### ISSUE TITLE
Custom Spawn Eggs - Bug

### ISSUE THREAD

**Issue by mrch0c0late** [b0iizz/minecraft-advancednbttooltip#3]
The "RepairCost" tooltip shows up on every custom spawn egg [example: **/give @p vindicator_spawn_egg{EntityTag:{id:"minecraft:illusioner"}}**]

![custom_spawn_egg](https://user-images.githubusercontent.com/55633098/95900201-d5018e00-0d91-11eb-9b95-1b1efb3f54d6.png)

**Comment by b0iizz** [comment]
This is probably related to the renaming of the item as I can't reproduce your issue with the provided command but I'll change it so that a RepairCost of 0 will not be shown. This way, a renamed item should not show a RepairCost unless it has actually been, for example, enchanted.
