### ISSUE TITLE
ShulkerBoxTooltip preview not rendering for item-frame/floating items

### ISSUE THREAD

**Issue by sudofox** [b0iizz/minecraft-advancednbttooltip#30]
This mod is super cool, but I'm having an issue where the [ShulkerBoxTooltip](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip) prompts on the item are shown but don't actually render for whatever reason when I press the keys. Can this be remedied?

![Screenshot from 2022-01-18 15-38-26](https://user-images.githubusercontent.com/3847441/150015010-4b7364f2-2322-46f6-83ea-5f1e925b6766.png)
![Screenshot from 2022-01-18 15-39-40](https://user-images.githubusercontent.com/3847441/150015046-0901a47e-3f67-4527-bcc1-fffcbc85917c.png)

**Comment by b0iizz** [comment]
I hope this fixes it. I'm going to release this soon hopefully. Thank you for bringing this issue to me!

**Comment by sudofox** [comment]
will it update on curseforge soon? ty
