### ISSUE TITLE
Creative Inventory Makes Toggles Not Work

### ISSUE THREAD

**Issue by RooftopJoe** [b0iizz/minecraft-advancednbttooltip#36]
If you grab an item from the Creative inventory, none of the toggles will work anymore. Turning custom tooltips off and back on again won't fix the issue. The only fix, as far as I've noticed, is restarting the game. Haven't tested for HUD tooltips.

**Comment by b0iizz** [comment]
I cannot reproduce the same thing you mention, but the "Search"-Menu seems to prevent the Tooltips from being shown
