### ISSUE TITLE
Request: Support for 1.19?

### ISSUE THREAD

**Issue by Antiflux** [b0iizz/minecraft-advancednbttooltip#39]
I've been using this mod for a fair while now, and although I had to override the version dependency, it still worked well for me through Minecraft 1.18.2. On version 1.19 I am unable to complete game initialization when I have this mod enabled. Would you consider producing a version that explicitly supports version 1.19?

**Comment by b0iizz** [comment]
I'm on it!

**Comment by b0iizz** [comment]
The update is public. I am sorry that i could not deliver sooner. I was not that often on my PC due to being away regularly.
