### ISSUE TITLE
Crash Log when hovering Filled Shulker Box

### ISSUE THREAD

**Issue by ardissaps** [b0iizz/minecraft-advancednbttooltip#40]
https://paste.atlauncher.com/view/be0ba75d-7179-4cb9-b0d2-9828c6d8218a

**Comment by b0iizz** [comment]
Does the same issue occur without my mod or is it fixed if you remove AdvancedNBTTooltips?

**Comment by ardissaps** [comment]
It does not happen without mod. I am using maybe conflict with [EasyShulkerBox](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes)?

**Comment by b0iizz** [comment]
Probably

**Comment by b0iizz** [comment]
I think this is the same issue as #41

**Comment by ardissaps** [comment]
Look like it was conflict with [ShetipianCore](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore), which was recently causing crash with shulkerbox but have been fixed. I will test again today.

**Comment by hexadecimal233** [comment]
I found out commit f0ad35a9a4b394f554035f42bc5dba31044494ab is the cause of the crash
