### ISSUE TITLE
Crashes when hovering over a map

### ISSUE THREAD

**Issue by DewGaming** [b0iizz/minecraft-advancednbttooltip#41]
[crash-2022-07-24_18.21.52-client.txt](https://github.com/b0iizz/minecraft-advancednbttooltip/files/9176929/crash-2022-07-24_18.21.52-client.txt)

**Comment by b0iizz** [comment]
This is probably due to an incompatibility with another mod. I will look into fixing these incompatibilities in the coming weeks

**Comment by b0iizz** [comment]
I did not comply with a changed API so my mod does not recognize custom tooltip data. I will change that as soon as I am able to get back to my PC, which will probably be in a week.
