### ISSUE TITLE
Since 1.19, AdvancedNBTTooltip 1.8.1 seems to interfere with ShulkerBox Preview mods

### ISSUE THREAD

**Issue by jr0dsgarage** [b0iizz/minecraft-advancednbttooltip#42]
I normally use Tweakaroo for shulker box tooltips, which show all contents of a shulker box when using SHIFT key.  However after 1.19 upgrade, this no longer works. 

I tried using the ShulkerBoxTooltips mod instead, thinking it was an issue with Tweakaroo, but that would hard-crash the game anytime I moused over a shulker-box.

Disabling AdvancedNBTTooltip got rid of the issues in both of the other two mods.

**Comment by b0iizz** [comment]
This is the same issue as #41

**Comment by jr0dsgarage** [comment]
so as soon as I add AdvancedNBTTooltip 1.8.2 into my mod stack, I no longer get shulker tooltips.
