### ISSUE TITLE
minecraft crashes, whenever i open inventory (w mod for 1.19.3)

### ISSUE THREAD

**Issue by Organ-donor** [b0iizz/minecraft-advancednbttooltip#48]
here's log. need help, please.
[crash-2023-02-15_13.23.01-client.txt](https://github.com/b0iizz/minecraft-advancednbttooltip/files/10742381/crash-2023-02-15_13.23.01-client.txt)

**Comment by b0iizz** [comment]
I released a temporary version which disables the tooltips in the creative inventory until i find a solution for your problem. It should not crash with this version anymore

**Comment by Organ-donor** [comment]
yeah, thank you!
it got much better in v1.8.3b, no crashes now, and in SP it works exacly like you described. in MP, however, i can't see tooltips even if survival, but! when i open some server gui, like /ah (market/economy plugin), all tooltips are making comeback everywhere.
looking forward next mod version. again, my gratitude. =)
